### ISSUE TITLE
Feature Request: Working QR code for profile installation

### ISSUE THREAD

**Issue by jaxonashton** [bloomkd46/homebridge-XfinityHome#1]
### Is your feature request related to a problem? Please describe:

I've tried several times to use the pre-generated QR code to install the profile and it fails.

### Describe the solution you'd like:

A working QR code that allows for download of the profile.

### Describe alternatives you've considered:

Since I can't install the profile, I can't complete setup of the plugin.

### Node Version (optional):

v18.2.0

### NPM Version (optional):

8.9.0

### Homebridge Version (optional):

1.4.1

### Plugin Version:

homebridge-xfinityhome@0.0.40

### Operating System (optional):

Raspberian

**Comment by jaxonashton** [comment]
![IMG_3630](https://user-images.githubusercontent.com/3246415/170809740-4acd93ae-eb32-4ca0-92c8-c8a06a15372c.PNG)

The URL it's attempting to load is `undefined:585/cert`.

**Comment by bloomkd46** [comment]
I will look into this but for now manually open a website and go to `http://<ip or host name you use for homebridge>:585/cert` while the proxy server is running

**Comment by bloomkd46** [comment]
Also check to see if their are any errors in the homebridge log after starting the proxy server

**Comment by jaxonashton** [comment]
> I will look into this but for now manually open a website and go to `http://<ip or host name you use for homebridge>:585/cert` while the proxy server is running

Attempted to do this with `http://192.168.8.9:585/cert` after setting the proxy of `server: undefined | port: 585 | authentication: off/unchecked` under my network SSID, and received an error of _"Safari cannot open the page. The error was: "The URL can't be shown"_.

**Comment by jaxonashton** [comment]
> Also check to see if their are any errors in the homebridge log after starting the proxy server

No errors shown in the HB logs.

**Comment by bloomkd46** [comment]
Try setting the server field to `192.168.8.9`

**Comment by jaxonashton** [comment]
It went back to the same error message of 'cannot connect to server'.

**Comment by bloomkd46** [comment]
Ok, I will look into fixing this tomorrow

**Comment by jaxonashton** [comment]
Thank you so much, @bloomkd46. I'm very glad to see you've updated this plugin, and I'm happy to help test things out to ensure it's working properly. I'd love to see Xfinity Home integrated into HomeKit via this Homebridge plugin.

**Comment by bloomkd46** [comment]
It is successfully working for me and several others so it's weird that it isn't working for you. Especially since my server is also on a raspberry pi.

**Comment by jaxonashton** [comment]
> > Also check to see if their are any errors in the homebridge log after starting the proxy server
> 
> No errors shown in the HB logs.

I double-checked the log this morning and saw the following:

```
[28/05/2022, 12:06:36] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /startProxy
[28/05/2022, 12:06:37] [Homebridge UI] [homebridge-xfinityhome] Incoming Request: /proxyActive
[28/05/2022, 12:18:49] [Homebridge UI] [homebridge-xfinityhome] Terminating child process...
[28/05/2022, 12:18:50] [Homebridge UI] [homebridge-xfinityhome] Child process ended

**Comment by bloomkd46** [comment]
Those logs look normal, I just published v0.0.41 which should fix this problem. In node v18 they changed the IP type from 'IPv4' to 4. It should work now.

please let me know if it dosen't

**Comment by jaxonashton** [comment]
I can confirm that the IP is now showing in the config steps. I'll start the configuration process again later today and let you know how I make out. 

Thank you again for your continued support.

**Comment by jaxonashton** [comment]
Just attempted another new configuration and it's allowing me to scan the QR code and install the profile, however, after I follow the instructions, the screen never moves on to Part 2. The message at the bottom of the page says "If this page doesn't redirect open a browser on your then (ex. Safari)". Not sure what that's supposed to mean, as the instructions seem unfinished/unclear?

Also, once I add the proxy of `<IP>:585`, I can't seem to access the Internet to sign into the Xfinity Home app.

**Comment by bloomkd46** [comment]
The page has 2 more sections before you finish, by opening safari it will recognize that the proxy is receiving requests so it will show the next page.

**Comment by bloomkd46** [comment]
> Also, once I add the proxy of `<IP>:585`, I can't seem to access the Internet to sign into the Xfinity Home app.

You have to re-install a new profile after each setup and make sure that the proxy is still active when you open Xfinity home

**Comment by jaxonashton** [comment]
I spent some time tonight getting this working, and I'm able to arm/disarm the system as expected.

I'll consider the issue closed. Thank you for all of your help, @bloomkd46. This plugin is fantastic!
