### ISSUE TITLE
Bug Report: Glass Break Sensor Errors on Startup

### ISSUE THREAD

**Issue by rdeutsch3** [bloomkd46/homebridge-XfinityHome#16]
### Describe The Bug:

Restart Homebridge and system displays error messages about unsupported devices.

Master Glass Window Break: Unknown accessory!
Family Glass Window Break: Unknown accessory!

### To Reproduce:

Restart Homebridge

### Expected behavior:

No errors on startup

### Logs:

```shell
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Master Glass Window Break: Unknown accessory! [
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Master Glass Window Break: Please open an issue about this. [
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Master Glass Window Break: {[
[  "hardwareId": "114",[
[  "status": "online",[
[  "technology": "legacyAlarmPanel",[
[  "_links": {[
[    "self": {[
[      "href": "/client/icontrol/device/114"[
[    },[
[    "isBypassed": {[
[      "method": "POST",[
[      "href": "network/instances/114.0/points/isBypassed"[
[    },[
[    "label": {[
[      "method": "POST",[
[      "href": "network/instances/114.0/points/label"[
[    },[
[    "functionType": {[
[      "method": "POST",[
[      "href": "network/instances/114.0/points/functionType"[
[    }[
[  },[
[  "deletable": true,[
[  "deviceType": "sensor",[
[  "properties": {[
[    "isFaulted": false,[
[    "displayOrder": 2,[
[    "isBypassed": false,[
[    "label": "Master Glass Window Break",[
[    "functionType": "perimeter",[
[    "type": "window"[
[  },[
[  "name": "Master Glass Window Break",[
[  "id": "114.0",[
[  "deviceSubtype": "default",[
[  "trouble": [][
[} [
....
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Family Glass Window Break: Unknown accessory! [
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Family Glass Window Break: Please open an issue about this. [
[[1/10/2023, 2:08:07 PM] [[[Xfinity Home][ [Family Glass Window Break: {[
[  "hardwareId": "115",[
[  "status": "online",[
[  "technology": "legacyAlarmPanel",[
[  "_links": {[
[    "self": {[
[      "href": "/client/icontrol/device/115"[
[    },[
[    "isBypassed": {[
[      "method": "POST",[
[      "href": "network/instances/115.0/points/isBypassed"[
[    },[
[    "label": {[
[      "method": "POST",[
[      "href": "network/instances/115.0/points/label"[
[    },[
[    "functionType": {[
[      "method": "POST",[
[      "href": "network/instances/115.0/points/functionType"[
[    }[
[  },[
[  "deletable": true,[
[  "deviceType": "sensor",[
[  "properties": {[
[    "isFaulted": false,[
[    "displayOrder": 3,[
[    "isBypassed": false,[
[    "label": "Family Glass Window Break",[
[    "functionType": "perimeter",[
[    "type": "window"[
[  },[
[  "name": "Family Glass Window Break",[
[  "id": "115.0",[
[  "deviceSubtype": "default",[
[  "trouble": [][
[} [
....
```

### Config:

```shell
{
    "bridge": {
        "name": "ZZZ",
        "username": "0E:EE:84:98:C2:5B",
        "port": 51810,
        "pin": "255-19-737",
        "advertiser": "bonjour-hap",
        "bind": [
            "bond0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Xfinity Home",
            "refreshToken": ******
            "pin": "1597",
            "temperatureSensors": true,
            "logLevel": 3,
            "logWatchdogErrors": false,
            "_bridge": {
                "username": "0E:CA:A4:35:02:C7",
                "port": 52433
            },
            "platform": "XfinityHomePlatform"
        }
    ]
}
```

### Operating System:

Other

### Node Version:

v16.16.0

### NPM Version:

8.11.0

### Homebridge Version:

1.6.0

### Plugin Version:

3.0.4

**Comment by bloomkd46** [comment]
Sorry for the delay, please try version 3.2.0 and let me know if you have any further problems.

**Comment by rdeutsch3** [comment]
Still having startup errors with v3.4.1 installed.  The logs look the same as the original post.

**Comment by bloomkd46** [comment]
Please go into the homebridge settings, select `delete single cached accessory`, and delete the glass break sensors.

It has them saved as an unknown device and won't re-register them until they are removed

**Comment by rdeutsch3** [comment]
I deleted all the cached accessories as this is the only plugin running on this instance.  No joy.  Sorry.  Same as the Window sensors.

**Comment by rdeutsch3** [comment]
Updating with current log:
[7/11/2023, 10:30:40 AM] [Xfinity Home] Master Glass Window Break: Server Started 
[7/11/2023, 10:30:40 AM] [Xfinity Home] Master Glass Window Break: Unknown accessory! 
[7/11/2023, 10:30:40 AM] [Xfinity Home] Master Glass Window Break: Please open an issue about this. 
[7/11/2023, 10:30:40 AM] [Xfinity Home] Master Glass Window Break: {
  "hardwareId": "114",
  "status": "online",
  "technology": "legacyAlarmPanel",
  "_links": {
    "self": {
      "href": "/client/icontrol/device/114"
    },
    "isBypassed": {
      "method": "POST",
      "href": "network/instances/114.0/points/isBypassed"
    },
    "label": {
      "method": "POST",
      "href": "network/instances/114.0/points/label"
    },
    "functionType": {
      "method": "POST",
      "href": "network/instances/114.0/points/functionType"
    }
  },
  "deletable": true,
  "deviceType": "sensor",
  "name": "Master Glass Window Break",
  "id": "114.0",
  "trouble": [],
  "deviceSubtype": "default",
  "properties": {
    "isFaulted": false,
    "displayOrder": 2,
    "isBypassed": false,
    "label": "Master Glass Window Break",
    "functionType": "perimeter",
    "type": "window"
  }
} 
[7/11/2023, 10:30:40 AM] [Xfinity Home] Restoring existing accessory from cache: Family Glass Window Break
[7/11/2023, 10:30:40 AM] [Xfinity Home] Family Glass Window Break: Server Started 
[7/11/2023, 10:30:40 AM] [Xfinity Home] Family Glass Window Break: Unknown accessory! 
[7/11/2023, 10:30:40 AM] [Xfinity Home] Family Glass Window Break: Please open an issue about this. 
[7/11/2023, 10:30:40 AM] [Xfinity Home] Family Glass Window Break: {
  "hardwareId": "115",
  "status": "online",
  "technology": "legacyAlarmPanel",
  "_links": {
    "self": {
      "href": "/client/icontrol/device/115"
    },
    "isBypassed": {
      "method": "POST",
      "href": "network/instances/115.0/points/isBypassed"
    },
    "label": {
      "method": "POST",
      "href": "network/instances/115.0/points/label"
    },
    "functionType": {
      "method": "POST",
      "href": "network/instances/115.0/points/functionType"
    }
  },
  "deletable": true,
  "deviceType": "sensor",
  "name": "Family Glass Window Break",
  "id": "115.0",
  "trouble": [],
  "deviceSubtype": "default",
  "properties": {
    "isFaulted": false,
    "displayOrder": 3,
    "isBypassed": false,
    "label": "Family Glass Window Break",
    "functionType": "perimeter",
    "type": "window"
  }
}

**Comment by bloomkd46** [comment]
Merging with issue #15
