### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by jrarruda** [bloomkd46/homebridge-XfinityHome#2]
### Is your feature request related to a problem? Please describe:

After installing the new update (v.0.1.0) today (5/31) upon restarting homebridge I am receiving the below error. 
I have tried uninstalling and redoing the profile/proxy and generating a new refresh key and that is still not working. 

**ERROR MESSAGE**
[5/31/2022, 7:07:53 PM] [Xfinity Home] Failed To Login With Error: {
  name: 'Error',
  message: 'Request failed with status code 500',
  request: {
    method: 'POST',
    protocol: 'https:',
    host: 'xhomeapi-lb-prod.codebig2.net',
    path: '/client/icontrol/devices/cameras/startMultiAccess',
    headers: []
  },
  response: {
    statusCode: undefined,
    statusMessage: undefined,
    headers: {
      date: 'Tue, 31 May 2022 23:07:53 GMT',
      'content-type': 'application/json;charset=UTF-8',
      'content-length': '540',
      connection: 'keep-alive',
      'keep-alive': 'timeout=60',
      'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
      expires: '0',
      pragma: 'no-cache',
      'strict-transport-security': 'max-age=31536000 ; includeSubDomains',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'DENY',
      'x-vcap-request-id': 'b5c89e8c-903a-497d-62bf-b9895aeb7266',
      'x-xss-protection': '1; mode=block',
      'xh-auth': 'eyJ4NXUiOiJodHRwczovL3hob21lYXBpLWxiLXByb2QuYXBwcy5jbG91ZC5jb21jYXN0Lm5ldC9zZXJ2aWNlL2tleXMvZmFmOTI0MjgvY2VydCIsInZlciI6IjMiLCJraWQiOiJmYWY5MjQyOCIsImFsZyI6IlJTMjU2In0.eyJyb2xlIjoiUCIsInBhcnRuZXIiOiJjb21jYXN0IiwiaXNzIjoieGhvbWVhcGktcHJvZC1sYi5nMi5hcHAuY2xvdWQuY29tY2FzdC5uZXQiLCJhdXRoR3VpZCI6IjM2Njk1MzEwMTEwNjEwMjAxNkNvbWNhc3QuUlRWRSIsInBvZE5hbWUiOiJhcGkwMDAwMDAwMiIsInNpdGVJZCI6IjEwMDkxOTExNCIsInBvZEhvc3QiOiJhcGkwMDAwMDAwMi54ZmluaXR5aG9tZS5jb20iLCJhY2NvdW50TnVtYmVyIjoiODc3MzEwMDE1MDEwNzc5MSIsImNpbWFUb2tlbiI6ImU2ZWUzM2U1Nzk4NDFmY2UxNTM2YjZmZDk3MDAwNDBmMzQ4MmM3M2I4MjZmMDExMGI1ZTc0YWE4NTA2NTU1MTUiLCJpYXQiOjE2NTQwMzg0NjgsImNvb2tpZXMiOnsiSlNFU1NJT05JRCI6IkxEZ2NZQmJMWE5FZlFUcHdLQ05OeTRrckVEd0I0WnlXNXpFb3J0U204T0N1MkhIRWtXUGkhMTQ2NzIzOTUzNCIsIlBvZEJYZmluaXR5SG9tZS00Nzg3My1wX3hocG9kYl9wb3J0YWxhcHBpbnRlcmZhY2UiOiJDREpPSENHQUZBQUEifX0.HkMEOvlMxRCySBE1D0zIhUAGrftaTjfdTHT6z4MPBjOESG4_xcwgUqGfU3P0Wm16nwiif86SMouB19LCYTGUYC0pj2f50Q5i1ZJjSgTQfkskEegTwVHYAQbvejMvuwml3FdpQl7aLSnmMdS62hvlRPGQX6v08eXZxjB1UqK0Fzj-KmP33VIpRGMzw0coKQT6siErdxXmxUZUEti6KXGevq0lo5rLySz_5IuS29iEsK8DaC5itRn6WeogWcyrgDyM7ivazrY1flQsy3bmJZXUYDWfTCVSqQYpLmARHYEyqL1AyOyUo_wP1QKL_sm28IUCFkvapF-7a0cEs5jt0tEndw',
      xh_fingerprint: '52cbd2df-1f10-43b1-b446-110e73d41b86',
      via: '1.1 CodeBig'
    },
    data: {
      timestamp: '2022-05-31T23:07:53.840Z',
      path: '/client/icontrol/devices/cameras/startMultiAccess',
      method: 'POST',
      fingerprint: '52cbd2df-1f10-43b1-b446-110e73d41b86',
      errorCode: 'UNKNOWN',
      exception: [Object],
      rootCause: [Object]
    }
  }
}

### Describe the solution you'd like:

Be able to run homebridge-XfinityHome 

### Node Version (optional):

v16.15.0 

### Homebridge Version (optional):

1.4.1

### Plugin Version:

v.0.1.0

**Comment by bloomkd46** [comment]
please try version 0.1.1 and let me know if this issue persists

**Comment by jrarruda** [comment]
Awesome, that worked like a charm. You are a life saver! Thank you again

**Comment by jrarruda** [comment]
Awesome, that worked like a charm. You are a life saver! Thank you again
