### ISSUE TITLE
Feature Request: Add Safari Note

### ISSUE THREAD

**Issue by rdeutsch3** [bloomkd46/homebridge-XfinityHome#27]
### Is your feature request related to a problem? Please describe:

I couldn't get the proxy certificate to download using my Synology Diskstation configuration.  Then when I switched to a standalone homebridge server to obtain the refresh token, I couldn't get the certificate to install in iOS using Firefox.

### Describe the solution you'd like:

Please update the installation/configuration page with the following:
Note: The Xfinity plug-in cannot be configured on Synology Diskstation Homebridge.  Please use standalone Homebridge or HOOBs and transfer the configuration after the refresh key is obtained.
Rationale: the proxy certificate never loads on my Diskstation configuration, it just stalls forever at loading.  Something happened with a power outage and the plugin lost contact with XFinity.  Try as I might I couldn't get the proxy to load to refresh the token.  Temporarily installed on my standalone Homebridge server and viola!  Certificate loaded and I then had a vague memory about using Safari last time (see below).

Add a Note something like the following:
-Ensure the default iOS browser is set to Safari, for the proxy certificate to be installed into the iOS Settings.

Rationale:  Only Safari worked for me.  Firefox just kept downloading the certificate, but not allowing me to do anything with it.

### Describe alternatives you've considered:

I tried using other browsers but only Safari would work to get the refresh token.

### Operating System (optional):

None

### Node Version (optional):

v16.16.0

### Homebridge Version (optional):

1.6.1

### Plugin Version:

3.0.5

**Comment by bloomkd46** [comment]
v3.4.2-beta.4

**Comment by bloomkd46** [comment]
v3.4.2
