### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by albertshih3** [bloomkd46/homebridge-XfinityHome#3]
### Is your feature request related to a problem? Please describe:

After setting up using the provided instructions, I am receiving an "Internal Server Error" with error code 500 and it does not log in. I tried updating to a beta version of the plugin as well but that does not work either. (Was originally running the latest version 0.1.1)

### Describe the solution you'd like:

Login works

### Describe alternatives you've considered:

Updating to beta

### Node Version (optional):

16.15.0

### Homebridge Version (optional):

1.4.1

### Plugin Version:

0.1.1

### Operating System (optional):

Windows

**Comment by bloomkd46** [comment]
Can you please post a copy of your logs

**Comment by albertshih3** [comment]
Here it is

`[6/5/2022, 8:00:16 PM] [Xfinity Home] Failed To Login With Error: {
  name: 'Error',
  message: 'Request failed with status code 500',
  request: {
    method: 'POST',
    protocol: 'https:',
    host: 'xhomeapi-lb-prod.codebig2.net',
    path: '/client/icontrol/devices/cameras/startMultiAccess',
    headers: [
      'POST /client/icontrol/devices/cameras/startMultiAccess HTTP/1.1',
      'Accept: application/json',
      'Content-Type: application/json',
      'Host: xhomeapi-lb-prod.codebig2.net',
      'Connection: keep-alive',
      'X-Client-Features: auth4all,carousel,carousel-devicedeeplink,no-cookie,deeplinkV1',
      'Xh-Auth: eyJ4NXUiOiJodHRwczovL3hob21lYXBpLWxiLXByb2QuYXBwcy5jbG91ZC5jb21jYXN0Lm5ldC9zZXJ2aWNlL2tleXMvZmFmOTI0MjgvY2VydCIsInZlciI6IjMiLCJraWQiOiJmYWY5MjQyOCIsImFsZyI6IlJTMjU2In0.eyJyb2xlIjoiUCIsInBhcnRuZXIiOiJjb21jYXN0IiwiaXNzIjoieGhvbWVhcGktcHJvZC1sYi5nMS5hcHAuY2xvdWQuY29tY2FzdC5uZXQiLCJhdXRoR3VpZCI6Ijg2ODg5NjMxOTgwMzMzMTA0MTYwMjIwMjAuSU1TIiwicG9kTmFtZSI6ImFwaTAwMDAwMDAyIiwic2l0ZUlkIjoiMTAxODI3NDAzIiwicG9kSG9zdCI6ImFwaTAwMDAwMDAyLnhmaW5pdHlob21lLmNvbSIsImFjY291bnROdW1iZXIiOiI4MTU1NDAwNTcyMTQxMzIxIiwiY2ltYVRva2VuIjoiYjNhZWY5N2M2ZTVlNzczYjM5MzNiOGYwZGU5OTZjZWY0NTU5ZjRhYTE2YjU3N2M5YWFhYzYzN2E2NmQzNTFiNiIsImlhdCI6MTY1NDQ4NDQxMywiY29va2llcyI6eyJKU0VTU0lPTklEIjoidjBVMjlLdFNtT0gtbjU3a0JkWjk5WVZKMEpYSWtFa21odElVY1B1TkhxWUJPMEpvQUVHRyExMzI0NDYyMzkxIiwiUG9kQlhmaW5pdHlIb21lLTQ3ODczLXBfeGhwb2RiX3BvcnRhbGFwcGludGVyZmFjZSI6IkJKSk9IQ0dBRkFBQSJ9fQ.j4Z5mbeTMXt1gqzdRvf9Vg-78VI7_xiURVDGZLwlQsTsWMORHVqe1q4f0VbmBT-MIAue74HdBNwnQFbW3enOOo9L7sgWACxDlJiR3kigpkf6FUYQqrQMZV7yqZw_Y-uZDogvHvPLwskGPgPOHa2MwPFiuqrZ6_D5nhBqquNORLntH_m92i-t7D-BADzclj1CGOQREptTszLeMgkcPx4NKl9W5CrTDlST8wGCmS7Gs-Mlbt_-d7_r_AMNSm1xnH62mJs9bfTpeD-7DaE39_Lg8zFQMNuI8nCxE67ca410-3uONlXpTGh7IiyvSPRB6hATCGunYH-sM02r7Si7bbN8VQ',
      'Authorization: Bearer CgNPQVQQARgCIoABJWseJVeioFOsF1c7V6DTNpQLNcdoGhOgNNAUHllSYm0f3Y26AL3WoowDOGYsexDW2LlcvAN0hWPmqTlyNDDRQhREuxlKomaOv74m20vfU5LoWrFbLlk5tTZQ4iQp2BotBJ3Wc2f89gz_JAckxg5UlQ5q4tyIMG1pWoWVfI9t6WkqEOpiRDqKIeWvxrvsZYCaadcyUQoodXJuOmNpbWE6b2F1dGg6djI6YWNjZXNzLXRva2VuOmVuY3J5cHQ6MRIldXJuOmNpbWE6b2F1dGg6djI6YWNjZXNzLXRva2VuOnNpZ246MTrAA9pVNJqXrK72KxkjrgvhgNhesEYXLKsuD6QbTDWLez8TYF9uvtQO5Cp4ldZNQbxE-uJ0oCtCZuOr8l-wtUfNVUELHJyDh3A1srtpzzID2OrwS5th235O-WgajictIlKaA4ngDowZzHCJZRWBlcMHNSZEVSyPggfC2HMoLBLSYEKTD2vToBGTf4YTt_z2H-MxcFeptxjjKTE1iaCibuWExDCLbsx7jtIJjqlAtDBX5a06OiCbPDXXUBz9Z8vzipkNrW09-aNRShIQ-GKVIW8ih1TGRgEJAXlQJIrdHxH80lYq17d1SoGYVMkPXv61ZRWfYsOajsENHwigrI-sATkCfbW0cjBmOvSsvJn-DjrZS5MuXL1YmZ9cgiHS-fN2ec8dyLtojH4yP2-RG8liK62MlMIUx-dHZluxjZKpQ7JfAVP_GnBWCG7ZMAQy3WWH0QziXIFxC_h7gDM7nlEwv0DZluxKR_UGDxbUGLUc4YmZl-DJOAdNP97mGyHJv6a5duD8iVyFzZdSvQ9-mGSXSCQQO760ZtI5_ayDceldGmr8x67obroF-bDu04vWWilXC2WVx5JAEVXBZnv-OuH0PfQkFgw*',
      'Accept-Language: en-us',
      'Accept-Encoding: gzip, deflate, br',
      'Content-Length: 237',
      'User-Agent: axios/0.26.1'
    ]
  },
  response: {
    statusCode: 500,
    statusMessage: 'Internal Server Error',
    headers: {
      date: 'Mon, 06 Jun 2022 03:00:18 GMT',
      'content-type': 'application/json;charset=UTF-8',
      'content-length': '540',
      connection: 'keep-alive',
      'keep-alive': 'timeout=60',
      'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
      expires: '0',
      pragma: 'no-cache',
      'strict-transport-security': 'max-age=31536000 ; includeSubDomains',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'DENY',
      'x-vcap-request-id': '7983c296-3652-4f28-54e3-1e04563ba4b4',
      'x-xss-protection': '1; mode=block',
      'xh-auth': 'eyJ4NXUiOiJodHRwczovL3hob21lYXBpLWxiLXByb2QuYXBwcy5jbG91ZC5jb21jYXN0Lm5ldC9zZXJ2aWNlL2tleXMvZmFmOTI0MjgvY2VydCIsInZlciI6IjMiLCJraWQiOiJmYWY5MjQyOCIsImFsZyI6IlJTMjU2In0.eyJyb2xlIjoiUCIsInBhcnRuZXIiOiJjb21jYXN0IiwiaXNzIjoieGhvbWVhcGktcHJvZC1sYi5nMS5hcHAuY2xvdWQuY29tY2FzdC5uZXQiLCJhdXRoR3VpZCI6Ijg2ODg5NjMxOTgwMzMzMTA0MTYwMjIwMjAuSU1TIiwicG9kTmFtZSI6ImFwaTAwMDAwMDAyIiwic2l0ZUlkIjoiMTAxODI3NDAzIiwicG9kSG9zdCI6ImFwaTAwMDAwMDAyLnhmaW5pdHlob21lLmNvbSIsImFjY291bnROdW1iZXIiOiI4MTU1NDAwNTcyMTQxMzIxIiwiY2ltYVRva2VuIjoiYjNhZWY5N2M2ZTVlNzczYjM5MzNiOGYwZGU5OTZjZWY0NTU5ZjRhYTE2YjU3N2M5YWFhYzYzN2E2NmQzNTFiNiIsImlhdCI6MTY1NDQ4NDQxMywiY29va2llcyI6eyJKU0VTU0lPTklEIjoidjBVMjlLdFNtT0gtbjU3a0JkWjk5WVZKMEpYSWtFa21odElVY1B1TkhxWUJPMEpvQUVHRyExMzI0NDYyMzkxIiwiUG9kQlhmaW5pdHlIb21lLTQ3ODczLXBfeGhwb2RiX3BvcnRhbGFwcGludGVyZmFjZSI6IkJKSk9IQ0dBRkFBQSJ9fQ.j4Z5mbeTMXt1gqzdRvf9Vg-78VI7_xiURVDGZLwlQsTsWMORHVqe1q4f0VbmBT-MIAue74HdBNwnQFbW3enOOo9L7sgWACxDlJiR3kigpkf6FUYQqrQMZV7yqZw_Y-uZDogvHvPLwskGPgPOHa2MwPFiuqrZ6_D5nhBqquNORLntH_m92i-t7D-BADzclj1CGOQREptTszLeMgkcPx4NKl9W5CrTDlST8wGCmS7Gs-Mlbt_-d7_r_AMNSm1xnH62mJs9bfTpeD-7DaE39_Lg8zFQMNuI8nCxE67ca410-3uONlXpTGh7IiyvSPRB6hATCGunYH-sM02r7Si7bbN8VQ',
      xh_fingerprint: '53879fdd-63f4-4538-bc6a-4bbc9d06eca6',
      via: '1.1 CodeBig'
    },
    data: {
      timestamp: '2022-06-06T03:00:18.073Z',
      path: '/client/icontrol/devices/cameras/startMultiAccess',
      method: 'POST',
      fingerprint: '53879fdd-63f4-4538-bc6a-4bbc9d06eca6',
      errorCode: 'UNKNOWN',
      exception: [Object],
      rootCause: [Object]
    }
  }
}`

**Comment by bloomkd46** [comment]
Do you have any cameras on your account?

**Comment by albertshih3** [comment]
Yes I do!

**Comment by bloomkd46** [comment]
Is it working now after a plug-in reboot by chance? Sometimes Comcast's goes down which is what this is looking like.

**Comment by albertshih3** [comment]
No, it still does not work.

**Comment by bloomkd46** [comment]
Can you try setting the debug variable to `XHome:Debug` in your homebridge server settings. Once you do that post the new log that will show up right before the error

**Comment by albertshih3** [comment]
Here you go:
`2022-06-07T00:28:38.534Z XHome:Debug {
  videoTokenAppKey: 'comcastTokenKey',
  cameras: [
    {
      instanceId: 'xbo:7722351418433294201',
      codec: 'MPEG4',
      format: 'MJPEG'
    },
    {
      instanceId: 'xbo:3209404512686917578',
      codec: 'MPEG4',
      format: 'MJPEG'
    }
  ],
  alwaysSendCameraAccessEventFlag: true
}
[6/6/2022, 5:28:38 PM] [Xfinity Home] Failed To Login With Error: {
  name: 'Error',
  message: 'Request failed with status code 500',
  request: {
    method: 'POST',
    protocol: 'https:',
    host: 'xhomeapi-lb-prod.codebig2.net',
    path: '/client/icontrol/devices/cameras/startMultiAccess',
    headers: [
      'POST /client/icontrol/devices/cameras/startMultiAccess HTTP/1.1',
      'Accept: application/json',
      'Content-Type: application/json',
      'Host: xhomeapi-lb-prod.codebig2.net',
      'Connection: keep-alive',
      'X-Client-Features: auth4all,carousel,carousel-devicedeeplink,no-cookie,deeplinkV1',
      'Xh-Auth: eyJ4NXUiOiJodHRwczovL3hob21lYXBpLWxiLXByb2QuYXBwcy5jbG91ZC5jb21jYXN0Lm5ldC9zZXJ2aWNlL2tleXMvZmFmOTI0MjgvY2VydCIsInZlciI6IjMiLCJraWQiOiJmYWY5MjQyOCIsImFsZyI6IlJTMjU2In0.eyJyb2xlIjoiUCIsInBhcnRuZXIiOiJjb21jYXN0IiwiaXNzIjoieGhvbWVhcGktcHJvZC1sYi5nMS5hcHAuY2xvdWQuY29tY2FzdC5uZXQiLCJhdXRoR3VpZCI6Ijg2ODg5NjMxOTgwMzMzMTA0MTYwMjIwMjAuSU1TIiwicG9kTmFtZSI6ImFwaTAwMDAwMDAyIiwic2l0ZUlkIjoiMTAxODI3NDAzIiwicG9kSG9zdCI6ImFwaTAwMDAwMDAyLnhmaW5pdHlob21lLmNvbSIsImFjY291bnROdW1iZXIiOiI4MTU1NDAwNTcyMTQxMzIxIiwiY2ltYVRva2VuIjoiOWM0YWY2MTM5ZGU2NGYzNmFmYWM2NzZlMmJhMGUzMWY1ZGNiOTVlOWIzYmZhOGZjNjIwMzRjMjU2MjU3OWVlMiIsImlhdCI6MTY1NDU2MTcxNSwiY29va2llcyI6eyJKU0VTU0lPTklEIjoiRGNRN2tEUF9pQy1HT2JoeDJqRnhMWXhVZnhLSkpmcFBqcWhFb2NMN2k1ekxQZjItUm9ESiExMzI0NDYyMzkxIiwiUG9kQlhmaW5pdHlIb21lLTQ3ODczLXBfeGhwb2RiX3BvcnRhbGFwcGludGVyZmFjZSI6IkJKSk9IQ0dBRkFBQSJ9fQ.BQbljAld2aKw5OGPeqKzBvM4riUvR4IbfuZ2KY4cSEUv1NNfNsm1Iq1KuHUm5j8D4yYcowmFeUnmpOpNc2MOAP0YEKduF4rxX_6drvYbxvULlpyrRpgtrkjwgif163d9lIN3zcemAhrAxHD9SYlQMEwwBESJ3KLwUGV78lsjwcfSc7Oh7C7PBBmT46XeRXhQQ6VospPcNFLxKKCZrGFwQUjkeAGx7h36roZmbpjEj6fzH0EL22CfRsfSDxV1BP8NozUTQNBw4crNHgsNf0wUOIWXlCG97JmfgOtv5BuKu1EIXLMz8-tpKm4s6YQRfpsYQTZ5OvkS-qvsmgg3AeX7gg',
      'Authorization: Bearer CgNPQVQQARgCIoABNR2sH8FawixxntPaY_6V5gUqlYxHLr3OZ5uvbsGgGdyamPHAYud9ZsAMH8vyQ6yFXorC3aTpcVH_VlQ3uA5YfS_xbHqSq_LFTYB_qQbnUU4tLAX8MwzJRM8PrEGi6gnGY4b-m7yrDyw2LNtX7mjYAikKfTttCcfBvDuMOtPPTOgqED8C3yt-c7XQ07d6rAPysEAyUQoodXJuOmNpbWE6b2F1dGg6djI6YWNjZXNzLXRva2VuOmVuY3J5cHQ6MRIldXJuOmNpbWE6b2F1dGg6djI6YWNjZXNzLXRva2VuOnNpZ246MTrAA6Z7YKv-NVJKFZUUrgpC9NysOEpdydtFzrSx89gOv6KuH1xtIoPt5nAfddjOHBmYNUVTVJfosKzRTUkzllTr7sombpDLYJw-gxGmjUaIzs_bDb9ZaFSRd2Zusi3eAq2TNIOaGvc_kHcBXxjpFLkSzx6HhlkOAqMhBWUACC9tnRL8tQObprn6sZgAA8ptAtrJuipj0RH0sqGbVZSdBqdl3eeIahA4WmtU_QFTyltuArYLa5Zd7dCDV4pYYXOdPp_eM704fYlFPZcKOuI4J4g3IZkv_nKg07xGzlEgev3pU7H9OJ-TgOlBhfSUck0l-ivpT3Wmv1liNOtcg_J1WSR1hheVF9_8tTyZjbeVY2hIjkQIEVBODXo-sfg9qO4fB7KrQ5eGbCklLrg0cdC6_vav5pJ3MUwR_JHmJWxs9DMLq2m-fZJ9p1F8ZpzesScqsKkWCO_V7nflT5WvE07CdAxh_ZtAqj-7mu2YiFFl2XXjKMZNkngcU-pPCPgadNynLz0mDjYX1LCI20btXeW-uWGh16H4OAiM1C_7X08FG5CcEHk-J7HtpuVjHS9WA2Qk4CxBhsL_DFE2FOXTQ5tcokd38bU*',
      'Accept-Language: en-us',
      'Accept-Encoding: gzip, deflate, br',
      'Content-Length: 237',
      'User-Agent: axios/0.26.1'
    ]
  },
  response: {
    statusCode: 500,
    statusMessage: 'Internal Server Error',
    headers: {
      date: 'Tue, 07 Jun 2022 00:28:39 GMT',
      'content-type': 'application/json;charset=UTF-8',
      'content-length': '540',
      connection: 'keep-alive',
      'keep-alive': 'timeout=60',
      'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
      expires: '0',
      pragma: 'no-cache',
      'strict-transport-security': 'max-age=31536000 ; includeSubDomains',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'DENY',
      'x-vcap-request-id': 'fe8e4b15-a823-49d8-52a6-5e73e6ff7548',
      'x-xss-protection': '1; mode=block',
      'xh-auth': 'eyJ4NXUiOiJodHRwczovL3hob21lYXBpLWxiLXByb2QuYXBwcy5jbG91ZC5jb21jYXN0Lm5ldC9zZXJ2aWNlL2tleXMvZmFmOTI0MjgvY2VydCIsInZlciI6IjMiLCJraWQiOiJmYWY5MjQyOCIsImFsZyI6IlJTMjU2In0.eyJyb2xlIjoiUCIsInBhcnRuZXIiOiJjb21jYXN0IiwiaXNzIjoieGhvbWVhcGktcHJvZC1sYi5nMS5hcHAuY2xvdWQuY29tY2FzdC5uZXQiLCJhdXRoR3VpZCI6Ijg2ODg5NjMxOTgwMzMzMTA0MTYwMjIwMjAuSU1TIiwicG9kTmFtZSI6ImFwaTAwMDAwMDAyIiwic2l0ZUlkIjoiMTAxODI3NDAzIiwicG9kSG9zdCI6ImFwaTAwMDAwMDAyLnhmaW5pdHlob21lLmNvbSIsImFjY291bnROdW1iZXIiOiI4MTU1NDAwNTcyMTQxMzIxIiwiY2ltYVRva2VuIjoiOWM0YWY2MTM5ZGU2NGYzNmFmYWM2NzZlMmJhMGUzMWY1ZGNiOTVlOWIzYmZhOGZjNjIwMzRjMjU2MjU3OWVlMiIsImlhdCI6MTY1NDU2MTcxNSwiY29va2llcyI6eyJKU0VTU0lPTklEIjoiRGNRN2tEUF9pQy1HT2JoeDJqRnhMWXhVZnhLSkpmcFBqcWhFb2NMN2k1ekxQZjItUm9ESiExMzI0NDYyMzkxIiwiUG9kQlhmaW5pdHlIb21lLTQ3ODczLXBfeGhwb2RiX3BvcnRhbGFwcGludGVyZmFjZSI6IkJKSk9IQ0dBRkFBQSJ9fQ.BQbljAld2aKw5OGPeqKzBvM4riUvR4IbfuZ2KY4cSEUv1NNfNsm1Iq1KuHUm5j8D4yYcowmFeUnmpOpNc2MOAP0YEKduF4rxX_6drvYbxvULlpyrRpgtrkjwgif163d9lIN3zcemAhrAxHD9SYlQMEwwBESJ3KLwUGV78lsjwcfSc7Oh7C7PBBmT46XeRXhQQ6VospPcNFLxKKCZrGFwQUjkeAGx7h36roZmbpjEj6fzH0EL22CfRsfSDxV1BP8NozUTQNBw4crNHgsNf0wUOIWXlCG97JmfgOtv5BuKu1EIXLMz8-tpKm4s6YQRfpsYQTZ5OvkS-qvsmgg3AeX7gg',
      xh_fingerprint: 'cf5fc072-49ec-49dd-a1cf-563836062d38',
      via: '1.1 CodeBig'
    },
    data: {
      timestamp: '2022-06-07T00:28:39.381Z',
      path: '/client/icontrol/devices/cameras/startMultiAccess',
      method: 'POST',
      fingerprint: 'cf5fc072-49ec-49dd-a1cf-563836062d38',
      errorCode: 'UNKNOWN',
      exception: [Object],
      rootCause: [Object]
    }
  }
}`

**Comment by bloomkd46** [comment]
Sorry For The Delay,
I just published version 0.1.2 which should fix this issue

**Comment by albertshih3** [comment]
Awesome! I'll try it right now and let you know if it is fixed!

**Comment by albertshih3** [comment]
Awesome it all works! (minus the cameras ofc but I know you're working hard on it) Thanks for the help :)
