### ISSUE TITLE
Support Request: How to get xfinity token?

### ISSUE THREAD

**Issue by GeorgeSycip** [bloomkd46/homebridge-XfinityHome#32]
### Describe Your Problem:

I have HOOBS4 and installed the latest plugin.  I entered email and password and pin but was unable to successfully see any devices. the log says there's no token. how do I get the token? there also was no 2 factor authentication request.

### Expected behavior:

after installing the plug in and entering credentials, rebooting hoobs and or the hub, adding into home, i expect to see my security device accessories to ask to be placed into a room. this did not happen.

### Logs:

```shell
no longer at client house can't provide at this time.
```

### Config:

```shell
can't provide at this time.
```

### Operating System:

Raspberian

### Node Version:

latest

### NPM Version:

latest

### Homebridge Version:

latest

### Plugin Version:

latest

**Comment by bloomkd46** [comment]
Sorry for the late response. Unfortunately, this plugin does not support HOOBS as it implements a custom ui. 

See [here](https://github.com/seydx/homebridge-mercedesme/issues/26#issuecomment-791925834) for how it was handled on another plugin
