### ISSUE TITLE
Bug Report:  Proxy Not Working

### ISSUE THREAD

**Issue by Jrpadg** [bloomkd46/homebridge-XfinityHome#36]
### Describe The Bug:

I have reported and followed up on a problem with the token capture process through the proxy tool for this plugin.  I did get 1 response from the developer, but has since been unresponsive.

I realize the developer does this when they have time, but as responses have diminished or disappeared should we consider this plugin unsupported?

thank you for building this!  You work is greatly appreciated.  Should support for the plugin resume, I would be happy to donate to the developer.

### To Reproduce:

Download and configure token and proxy, attempt to run the tool then login to Xfinity to capture the token.  Phone says there is no internet connection, will not allow proxy tool to run or navigate to Xfinity login screen.

### Expected behavior:

Proxy tool to work - capture the token through following instructions.

### Logs:

```shell
Sent prior
```

### Config:

```shell
Sent prior
```

### Operating System:

Raspberian

### Node Version:

?

### NPM Version:

?

### Homebridge Version:

?

### Plugin Version:

?

**Comment by bloomkd46** [comment]
I apologize, I have been busy lately and forgot the issue was opened. I thought about it initially but no solutions came to mind. I will look into it more this week and see if I can figure it out. 

Other than that one issue,this plugin has been holding steady without any other issues. Unless other users come up with suggestions, I only plan to revisit implementing Eve temperature history support.

**Comment by Jrpadg** [comment]
Hello checking back in - any luck with this?

it would seem the issue is only around securing the token through the proxy tool.  I would recommend trying to run through that process again to invalidate or validate the issue.  This may reveal to you a workaround that wasn’t captured in instructions.  I suspect the reason you aren’t hearing much on this is for those who are already on it still works, but new people trying to join it doesn’t.

Just an update on my end.  Since I have been working on this, I have received 2 updates to Homebridge.  I also have tried rolling the plugin back to several different versions going back to 2.0.  I also disabled 2 factor authentication on my Xfinity Home account - all to no avail.

thank you again

**Comment by bloomkd46** [comment]
This issue affects more people than I realized. Sometime this week I will post a manual method for getting the refresh token using a (free) proxy app from the App Store.

**Comment by bloomkd46** [comment]
Merging with #37
