### ISSUE TITLE
Bug Report: Sensor values not updating

### ISSUE THREAD

**Issue by cmb991** [bloomkd46/homebridge-XfinityHome#4]
### Describe The Bug:

Sensor values not updating.  Tried multiple times to get different contact sensors to show open when they are in the open state. The sensor still show closed.

### To Reproduce:

Open a contact sensor and look at the HomeKit app sensor.

### Expected behavior:

Should show open.

### Logs:

```shell
N/A
```

### Config:

```shell
N/A
```

### Operating System:

Raspberian

### Node Version:

N/A

### NPM Version:

N/A

### Homebridge Version:

N/A

### Plugin Version:

N/A

**Comment by bloomkd46** [comment]
Is it showing that the sensor was opened/closed if you go to `homebridge ui`>`plugins`>`Xfinity Home Settings`>`logs`

**Comment by cmb991** [comment]
No.  Logs don’t show it opened then closed.  It doesn’t show open ever in the logs.

**Comment by cmb991** [comment]
Now it just worked.  Not sure what happen.

**Comment by bloomkd46** [comment]
I know that with mine every once in a while comcast will freeze, to know if that's what's happening you can always look at the Xfinity Home app on your phone and see if it's showing the same thing
