### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by cmb991** [bloomkd46/homebridge-XfinityHome#5]
### Describe Your Problem:

I’m still seeing inconsistencies in the sensor values.  For example, the front door opens, Xfinity Home App sends a push notification but sometimes HomeKit doesn’t see that sensor as open.  
The reason I see this is because my door lock is set to auto lock when the door sensor closes.
I had originally paid seydx to develop a plugin for Xfinity home (the unverified one), he had issues with the sensors not always passing through correctly and had to change the method he was getting the sensors.   

### Expected behavior:

As you can see in the screenshot, xFINITY Home shows that the door opened but along the top bar, the sensor never shows that it opened. It only will do it sometimes, so it’s not always picking up the presents are open.
![3A0C377B-6F7F-43F6-A75F-2AECB44B23BC](https://user-images.githubusercontent.com/30929454/178109814-24b2cae4-2cfc-496d-8cd7-148251e67b6f.jpeg)
![2CACC86A-7773-477E-A88E-782E7F0CBCFB](https://user-images.githubusercontent.com/30929454/178109815-41750285-8de6-4326-9e96-576e850ee32c.jpeg)

### Logs:

```shell
N/A
```

### Config:

```shell
N/A
```

### Operating System:

Docker

### Node Version:

N/A

### NPM Version:

N/A

### Homebridge Version:

N/A

### Plugin Version:

N/A

**Comment by bloomkd46** [comment]
If you go to the logs section in the custom ui, does it show any activity from the sensor?

**Comment by cmb991** [comment]
Just tested, logs show the door opened at 7:35.  I closed it a second later.  Logs show the door didn't close until 7:37 but you can see from the screenshot of the xfinity home app, the door closed at 7:35 also.
[https://imgur.com/a/Kb3Uhig](url)

**Comment by cmb991** [comment]
Its also not every time.  It works sometimes fine especially after I relink my account.

**Comment by bloomkd46** [comment]
Do you uninstall the app after you get the refresh token. If not the app could be using the token while waiting for changes which might block the plugin.

**Comment by cmb991** [comment]
No.  I have a separate account for the xfinity home homebridge login.  I delete the app after I'm done, I don't sign out.  Then I re download the app and sign in with my normal login.  So the session is still open on the homebrige one.

**Comment by bloomkd46** [comment]
Ok, that's the same setup I use so I'm not quite sure why it wouldn't be working. I might try something and publish it as a beta release for you to test out. I'll let you know if I do

**Comment by cmb991** [comment]
Is there any logs I can send you?

**Comment by bloomkd46** [comment]
It sounds like their aren't any to show as long as it's not sending error messages

**Comment by bloomkd46** [comment]
The one thing you could try is seti g the `DEBUG` variable in your homebridge settings to `XHome:Error*` (note: this requires you to restart your whole homebridge instance to take effect)

**Comment by cmb991** [comment]
Is there a support email I can send my log to so all my business isn’t out there?  Lol.  I can also send the screenshots from xfintiy home of the sensor activity.

**Comment by cmb991** [comment]
I had XHome:Error* set for the past few days.  It still does it plenty of times (sensor not triggering open and close).  Where should I send the logs?  What is the path to the logs I need to upload/send?

**Comment by bloomkd46** [comment]
Send it to me over discord if you don’t want them displayed publicly

**Comment by bloomkd46** [comment]
Please try version `3.0.0` (currently published as `3.0.0-beta.16`) and let me know if it fixes the problem.

**Comment by cmb991** [comment]
Won't even load, gets stuck on the gear wheel.  Did a homebridge restart and did a docker container restart, same issue.  Tried deleting the plugin and reinstalling multiple times.
<img width="788" alt="Screenshot 2022-12-24 at 10 44 35 PM" src="https://user-images.githubusercontent.com/30929454/209456381-5bf75a51-0b22-4cb2-b4c7-e27e3ac34a77.png">

**Comment by bloomkd46** [comment]
Can you please open up your browser console and send me any errors it has

**Comment by cmb991** [comment]
If I go back to 2.4.0, it lets me setup.  Anything in the 3.0.x is doing it.  
<img width="642" alt="Screenshot 2022-12-24 at 10 51 45 PM" src="https://user-images.githubusercontent.com/30929454/209456442-18782587-7542-436b-9eee-4c1d93c71bee.png">

**Comment by cmb991** [comment]
<img width="896" alt="Screenshot 2022-12-24 at 10 53 08 PM" src="https://user-images.githubusercontent.com/30929454/209456468-88debe0f-d23a-4165-8964-a165d1ced0f2.png">

**Comment by bloomkd46** [comment]
Could you please open up one of the errors and send me the content so that I can locate where in the file the error is

**Comment by cmb991** [comment]
This is all I'm seeing

<img width="1433" alt="Screenshot 2022-12-24 at 10 57 18 PM" src="https://user-images.githubusercontent.com/30929454/209456533-6f0b73f0-53de-4be0-9221-808ed37ea8db.png">

**Comment by bloomkd46** [comment]
Unfortunately, those errors are not originating from my plugin so I cannot provide much help for those. The only thing I can suggest is that you clear your browser cache after upgrading the plugin to ensure that isn’t loading old files for the ui. If that doesn’t work I recommend opening an issue on the homebridge-config-ui-x repository.

> Note: the config parameters did not have any breaking changes from the previous version so the plugin should still work

**Comment by cmb991** [comment]
I installed 2.4.0 and upgraded to 3.0.0.  Is that good for testing or do I need a clean install of 3.0.0?

**Comment by bloomkd46** [comment]
that should work fine

**Comment by cmb991** [comment]
Error 
![75138A6C-C5C7-411A-8678-514304B5381F](https://user-images.githubusercontent.com/30929454/209536825-e1e26604-a249-4fd2-a153-3e9ca7c18090.png)

**Comment by bloomkd46** [comment]
> Error
> ![75138A6C-C5C7-411A-8678-514304B5381F](https://user-images.githubusercontent.com/30929454/209536825-e1e26604-a249-4fd2-a153-3e9ca7c18090.png)

Patched `3.0.2`

**Comment by cmb991** [comment]
Confirmed working so far.
